Repository NarawishS/ku-hub, pull requests merged in 2020-11, with the labels that each got.

#44 Tags feature fixes and can be used correctly
  kuhub/admin.py
  kuhub/models/blog.py
  kuhub/templates/kuhub/create_blog.html
  kuhub/templates/kuhub/create_tag.html
  kuhub/templates/kuhub/search.html
  kuhub/urls.py
  kuhub/views/blog_view.py
  mysite/settings.py
Labels: bug, design

#55 Blog forum feature
  kuhub/admin.py
  kuhub/forms.py
  kuhub/models/blog.py
  kuhub/templates/kuhub/base.html
  kuhub/templates/kuhub/create_blog.html
  kuhub/templates/kuhub/forum_detail.html
  kuhub/templates/kuhub/forum_index.html
  kuhub/urls.py
  kuhub/views/blog_view.py
Labels: design, enhancement

#60 Blog Forum new features and bug fixes
  kuhub/models/blog.py
  kuhub/templates/kuhub/forum_index.html
  kuhub/urls.py
  kuhub/views/blog_view.py
Labels: bug, design, enhancement

#61 user blogs & create profile features
  kuhub/forms.py
  kuhub/templates/kuhub/base.html
  kuhub/templates/kuhub/forum_detail.html
  kuhub/templates/kuhub/profile_create.html
  kuhub/templates/kuhub/user_profile.html
  kuhub/views/blog_view.py
  kuhub/views/user_view.py
  mysite/urls.py
Labels: enhancement
